BossBar helper
Veltjs/Velt pull request #13
Opened 2021-03-26 20:36 UTC by MrScopes

this pr adds `bossbar` to velt/helpers

2021-03-26 21:22 UTC, Grabsky requested changes

2021-03-26 21:22 UTC, Grabsky commented on src/main/resources/@types/velt/helpers.d.ts
> +    /** The player's the bossbar is attached to. */
shouldn't this be `players`?

2021-03-27 23:03 UTC, Cormanz reviewed
Rename namespacekey method to namespaceKey
Make getBossBar, getBossBars, and createBossBar also part of helpers

2021-03-27 23:20 UTC, MrScopes commented
> Rename namespacekey method to namespaceKey
> Make getBossBar, getBossBars, and createBossBar also part of helpers

it's already a part of helpers?

2021-03-28 00:51 UTC, Cormanz commented
I mean helpers directly.

2021-03-28 01:12 UTC, MrScopes commented
> I mean helpers directly.

as in remove the crafting interface?

2021-03-28 02:15 UTC, Cormanz commented
Nah, I just mean add the bossbar methods directly to helpers as well as an alias.

2021-03-28 03:04 UTC, Cormanz commented
Alternatively bossbar.create and bossbar.get would be better since it doesn't mean you have to repeat the bossbar name twice

2021-03-28 16:55 UTC, Cormanz approved these changes

2021-03-28 16:58 UTC, merged